### ISSUE TITLE
BUG!  The world is still here!

### ISSUE THREAD

**Issue by aifartist** [ScyberJ/destroyTheWorld#1]
BUG!  The world is still here!  I expected full vaporization of the entire planet.

**Comment by ScyberJ** [comment]
Sadly this repo was abandoned due to the infeasibility of destroying the world with only the knowledge I have right now. Maybe I will continue development in the future once I have achieved my full potential in terms of world domination. You are welcome to continue development in case you also wish to destroy the world.
